/* Индексы тайлов в атласе текстур (8 колонок × 8 строк). */
export const T = {
  GRASS_TOP: 0, GRASS_SIDE: 1, DIRT: 2, STONE: 3,
  SAND: 4, WATER: 5, LOG_SIDE: 6, LOG_TOP: 7,
  LEAVES: 8, COAL: 9, IRON: 10, COPPER: 11,
  GOLD: 12, DIAMOND: 13, BEDROCK: 14, PLANKS: 15,
  CRAFTING_TOP: 16, CRAFTING_SIDE: 17,
  FURNACE_FRONT: 18, FURNACE_SIDE: 19, FURNACE_TOP: 20,
  GLASS: 21, BRICK: 22,
  CHEST_TOP: 23, CHEST_SIDE: 24, CHEST_FRONT: 25
};